-- 0008_charges_payments.sql
-- The financial core. Status is DERIVED from these tables, never stored. §7 rule 1.
-- All money is integer halalas (bigint). No float/double anywhere. §7 rule 3.
-- Every Charge is tax-ready from day one. §7 rule 2.

-- ---------------------------------------------------------------------------
-- Charge — a single due line generated by a contract (or ad-hoc). One row per due amount/date.
-- VAT fields present now so a compliant invoice needs no historical back-fill.
-- ---------------------------------------------------------------------------
create table app.charge (
  id                    uuid primary key default gen_random_uuid(),
  org_id                uuid not null references app.organization(id) on delete cascade,
  property_id           uuid not null references app.property(id),   -- denormalized for scope + perf
  unit_id               uuid references app.unit(id),
  contract_id           uuid references app.contract(id) on delete cascade,
  charge_type           app.charge_type not null,
  description           text,
  due_date              date not null,
  currency              text not null default 'SAR' check (currency = 'SAR'),
  amount_excl_vat_halalas bigint not null check (amount_excl_vat_halalas >= 0),
  vat_rate              numeric(5,4) not null default 0.0000 check (vat_rate >= 0 and vat_rate <= 1),
  vat_amount_halalas    bigint not null default 0 check (vat_amount_halalas >= 0),
  -- Generated: the gross due. Payments allocate against this.
  amount_incl_vat_halalas bigint generated always as
                          (amount_excl_vat_halalas + vat_amount_halalas) stored,
  created_by            uuid references app.identity(id),
  created_at            timestamptz not null default now(),
  updated_at            timestamptz not null default now(),
  deleted_at            timestamptz,
  deleted_by            uuid,
  deleted_reason        text
);

create index charge_org_idx      on app.charge (org_id) where deleted_at is null;
create index charge_contract_idx on app.charge (contract_id);
create index charge_property_idx on app.charge (property_id);
create index charge_due_idx      on app.charge (org_id, due_date) where deleted_at is null;

-- ---------------------------------------------------------------------------
-- Payment — money received. Separate from charges; matched via PaymentAllocation.
-- One payment can cover several charges; one charge can be covered by several payments.
-- ---------------------------------------------------------------------------
create table app.payment (
  id             uuid primary key default gen_random_uuid(),
  org_id         uuid not null references app.organization(id) on delete cascade,
  party_id       uuid references app.party(id),        -- payer (usually the tenant)
  method         app.payment_method not null default 'bank_transfer',
  amount_halalas bigint not null check (amount_halalas > 0),
  received_at    timestamptz not null default now(),
  reference      text,                                  -- bank ref / SADAD bill / gateway id
  notes          text,
  created_by     uuid references app.identity(id),
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now(),
  deleted_at     timestamptz,
  deleted_by     uuid,
  deleted_reason text
);

create index payment_org_idx   on app.payment (org_id) where deleted_at is null;
create index payment_party_idx on app.payment (party_id);

-- ---------------------------------------------------------------------------
-- PaymentAllocation — matches a payment to a charge for a specific amount.
-- Enforced invariants (trigger, 0011):
--   sum(alloc.amount) per payment <= payment.amount
--   sum(alloc.amount) per charge  <= charge.amount_incl_vat
-- Partial, late, overpayment, and one-payment-covers-two-charges all fall out of this. §10 test 12
-- ---------------------------------------------------------------------------
create table app.payment_allocation (
  id             uuid primary key default gen_random_uuid(),
  org_id         uuid not null references app.organization(id) on delete cascade,
  payment_id     uuid not null references app.payment(id) on delete cascade,
  charge_id      uuid not null references app.charge(id) on delete cascade,
  amount_halalas bigint not null check (amount_halalas > 0),
  created_at     timestamptz not null default now(),
  unique (payment_id, charge_id)
);

create index payment_allocation_payment_idx on app.payment_allocation (payment_id);
create index payment_allocation_charge_idx  on app.payment_allocation (charge_id);
