-- 0041_roles_matrix.sql
-- Sprint I: a real role → capability matrix, replacing the blunt "everyone-but-viewer can write" rule
-- from 0033. Five capabilities (view / manage_data / manage_finance / manage_team / manage_billing)
-- are mapped to the six roles, and the DB-level RESTRICTIVE write policies are re-expressed per
-- capability: data tables need manage_data, financial tables need manage_finance. `charge` counts as
-- manage_data (it is generated by the contract lifecycle). team/billing stay owner/admin (is_org_admin).
-- Idempotent.

-- The matrix (data — inspectable by the UI's role reference). Seeded here; not writable via the API.
create table if not exists app.role_capability (
  role       app.membership_role not null,
  capability text not null,
  primary key (role, capability)
);
insert into app.role_capability (role, capability) values
  ('owner','view'),('owner','manage_data'),('owner','manage_finance'),('owner','manage_team'),('owner','manage_billing'),
  ('admin','view'),('admin','manage_data'),('admin','manage_finance'),('admin','manage_team'),('admin','manage_billing'),
  ('manager','view'),('manager','manage_data'),('manager','manage_finance'),
  ('accountant','view'),('accountant','manage_finance'),
  ('staff','view'),('staff','manage_data'),
  ('viewer','view')
on conflict do nothing;

alter table app.role_capability enable row level security;
grant select on app.role_capability to authenticated;
drop policy if exists role_capability_select on app.role_capability;
create policy role_capability_select on app.role_capability for select using (true);

-- has_capability(org, cap) — active membership in the active org whose role carries the capability.
create or replace function app.has_capability(p_org uuid, p_capability text) returns boolean
language sql stable security definer set search_path = app, pg_temp as $$
  select app.has_org_access(p_org)
     and exists (
       select 1
       from app.membership m
       join app.role_capability rc on rc.role = m.role and rc.capability = p_capability
       where m.identity_id = auth.uid() and m.org_id = p_org
         and m.status = 'active' and m.deleted_at is null
     );
$$;

-- current_capabilities(org) — the caller's capability set, for the UI to hide/disable controls.
create or replace function app.current_capabilities(p_org uuid) returns text[]
language sql stable security definer set search_path = app, pg_temp as $$
  select case when app.has_org_access(p_org) then
    coalesce((
      select array_agg(distinct rc.capability)
      from app.membership m
      join app.role_capability rc on rc.role = m.role
      where m.identity_id = auth.uid() and m.org_id = p_org
        and m.status = 'active' and m.deleted_at is null
    ), '{}')
  else '{}' end;
$$;

revoke all on function app.has_capability(uuid, text)      from public;
revoke all on function app.current_capabilities(uuid)      from public;
grant execute on function app.has_capability(uuid, text)   to authenticated, service_role;
grant execute on function app.current_capabilities(uuid)   to authenticated, service_role;

-- ---------------------------------------------------------------------------
-- Re-express the RESTRICTIVE write policies per capability (replacing 0033's is_org_writer ones).
-- ---------------------------------------------------------------------------
-- manage_data tables (charge included — generated by contract activation/amendment).
do $$
declare t text;
begin
  foreach t in array array[
    'party','owner','tenant','property','building','unit','unit_status_history',
    'contract','contract_amendment','management_agreement','charge',
    'document','import_batch','import_row'
  ] loop
    execute format('drop policy if exists %I on app.%I', t || '_writer_ins', t);
    execute format('drop policy if exists %I on app.%I', t || '_writer_upd', t);
    execute format('drop policy if exists %I on app.%I', t || '_cap_ins', t);
    execute format('drop policy if exists %I on app.%I', t || '_cap_upd', t);
    execute format('create policy %I on app.%I as restrictive for insert with check (app.has_capability(org_id,''manage_data''))', t || '_cap_ins', t);
    execute format('create policy %I on app.%I as restrictive for update using (app.has_capability(org_id,''manage_data'')) with check (app.has_capability(org_id,''manage_data''))', t || '_cap_upd', t);
  end loop;
end $$;

-- manage_finance tables.
do $$
declare t text;
begin
  foreach t in array array['payment','payment_allocation','invoice','invoice_line','owner_remittance'] loop
    execute format('drop policy if exists %I on app.%I', t || '_writer_ins', t);
    execute format('drop policy if exists %I on app.%I', t || '_writer_upd', t);
    execute format('drop policy if exists %I on app.%I', t || '_cap_ins', t);
    execute format('drop policy if exists %I on app.%I', t || '_cap_upd', t);
    execute format('create policy %I on app.%I as restrictive for insert with check (app.has_capability(org_id,''manage_finance''))', t || '_cap_ins', t);
    execute format('create policy %I on app.%I as restrictive for update using (app.has_capability(org_id,''manage_finance'')) with check (app.has_capability(org_id,''manage_finance''))', t || '_cap_upd', t);
  end loop;
end $$;

-- payment_allocation DELETE → manage_finance.
drop policy if exists payment_allocation_writer_del on app.payment_allocation;
drop policy if exists payment_allocation_cap_del    on app.payment_allocation;
create policy payment_allocation_cap_del on app.payment_allocation as restrictive for delete
  using (app.has_capability(org_id, 'manage_finance'));

-- management_agreement_unit (no org_id) → manage_data via its parent agreement.
drop policy if exists mgmt_unit_writer_ins on app.management_agreement_unit;
drop policy if exists mgmt_unit_writer_upd on app.management_agreement_unit;
drop policy if exists mgmt_unit_writer_del on app.management_agreement_unit;
drop policy if exists mgmt_unit_cap_ins on app.management_agreement_unit;
drop policy if exists mgmt_unit_cap_upd on app.management_agreement_unit;
drop policy if exists mgmt_unit_cap_del on app.management_agreement_unit;
create policy mgmt_unit_cap_ins on app.management_agreement_unit as restrictive for insert
  with check (exists (select 1 from app.management_agreement a where a.id = agreement_id and app.has_capability(a.org_id,'manage_data')));
create policy mgmt_unit_cap_upd on app.management_agreement_unit as restrictive for update
  using (exists (select 1 from app.management_agreement a where a.id = agreement_id and app.has_capability(a.org_id,'manage_data')))
  with check (exists (select 1 from app.management_agreement a where a.id = agreement_id and app.has_capability(a.org_id,'manage_data')));
create policy mgmt_unit_cap_del on app.management_agreement_unit as restrictive for delete
  using (exists (select 1 from app.management_agreement a where a.id = agreement_id and app.has_capability(a.org_id,'manage_data')));
